deploy_env=dev
account_number=305068201745
aws_profile=jakshwealth
aws_credentials_id=
aws_region=ap-south-2
bucket_region_suffix=aps2
s3_ui_bucket=jakshwealth-ui-dev-aps2
account_email=jakshu2024@gmail.com
