deploy_env=test
account_number=305068201745
aws_profile=jakshwealth
aws_credentials_id=
aws_region=ap-south-2
bucket_region_suffix=aps2
s3_ui_bucket=jakshwealth.com
cloudfront_distribution_id=E2TQ76Z4FZC0WK
account_email=jakshu2024@gmail.com
