---
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: registry.cigna.com/enterprise-devops/conduit-jnlp:latest
    resources:
      requests:
        cpu: 150m
        memory: 1000Mi
      limits:
        cpu: 650m
        memory: 1000Mi
  - name: cloudkit
    image: registry.cigna.com/enterprise-devops/aws-d-cloudkit:plz-2-python-3.11
    command:
    - cat
    workingDir: /home/jenkins/agent
    imagePullPolicy: IfNotPresent
    tty: true
    resources:
      requests:
        cpu: 150m
        memory: 1000Mi
      limits:
        cpu: 650m
        memory: 1000Mi
  - name: ccdweb
    image: registry.cigna.com/h86233/hpp-web:latest
    tty: true
    command:
    - 'cat'
    resources:
      requests:
        cpu: "3375m"
        memory: "14336Mi"
      limits:
        cpu: "6750m"
        memory: "16384Mi"
    env:
    - name: NG_CLI_ANALYTICS
      value: "ci"
  - name: cx-toolshack
    image: registry-dev.cigna.com/dev-sec-ops/checkmarx-toolshack:1.1.0
    resources:
      requests:
        cpu: 150m
        memory: 150Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
    imagePullPolicy: Always
    workingDir: /home/jenkins/agent
    tty: true
